eureka:
  instance:
    hostname: purchase-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084
spring:
  application:
    name: Purchase-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/purchasedb
    username: root
    password: Abc@123456789
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

management:
  tracing:
    sampling:
      probability: 1.0