eureka:
  instance:
    hostname: shipping-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8087
spring:
  application:
    name: Shipping-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shipping-mysql:3306/shippingdb
    username: root
    password: Abc@123456789
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  config:
    payments-url: http://localhost:8222/api/v1/shippings

management:
  tracing:
    sampling:
      probability: 1.0