eureka:
  instance:
    hostname: api-gateway
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8222
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: users
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
management:
  tracing:
    sampling:
      probability: 1.0