eureka:
  instance:
    hostname: cart-service
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8083
spring:
  application:
    name: Cart-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3303/cartdb
    username: root
    password: Abc@123456789
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

application:
  config:
    carts-url: http://localhost:8222/api/v1/carts

management:
  tracing:
    sampling:
      probability: 1.0